// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-Bp4simmOpVhqhzSIR_BSaZGHyUjDH0',
    appId: '1:1050419105502:web:007b2487276b6196463c4f',
    messagingSenderId: '1050419105502',
    projectId: 'nava-sankalp',
    authDomain: 'nava-sankalp.firebaseapp.com',
    storageBucket: 'nava-sankalp.firebasestorage.app',
    measurementId: 'G-0Y8FR385GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgoHd7py_DrOwQjStR_-r_xoIzkOHiqGU',
    appId: '1:1050419105502:android:fb8c9ea7b11f2729463c4f',
    messagingSenderId: '1050419105502',
    projectId: 'nava-sankalp',
    storageBucket: 'nava-sankalp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCggpDVFL8UJ4xf8dB_5ulvArhwRuO0_bI',
    appId: '1:1050419105502:ios:5e9828f4afe59ed1463c4f',
    messagingSenderId: '1050419105502',
    projectId: 'nava-sankalp',
    storageBucket: 'nava-sankalp.firebasestorage.app',
    androidClientId: '1050419105502-11drvr2i9ro3hbt45snu7h7spph3hj9c.apps.googleusercontent.com',
    iosClientId: '1050419105502-ug3o34q66bqeh43d7glem347f6ue2u5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCggpDVFL8UJ4xf8dB_5ulvArhwRuO0_bI',
    appId: '1:1050419105502:ios:5e9828f4afe59ed1463c4f',
    messagingSenderId: '1050419105502',
    projectId: 'nava-sankalp',
    storageBucket: 'nava-sankalp.firebasestorage.app',
    androidClientId: '1050419105502-11drvr2i9ro3hbt45snu7h7spph3hj9c.apps.googleusercontent.com',
    iosClientId: '1050419105502-ug3o34q66bqeh43d7glem347f6ue2u5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3-Bp4simmOpVhqhzSIR_BSaZGHyUjDH0',
    appId: '1:1050419105502:web:e17c38800b5099b2463c4f',
    messagingSenderId: '1050419105502',
    projectId: 'nava-sankalp',
    authDomain: 'nava-sankalp.firebaseapp.com',
    storageBucket: 'nava-sankalp.firebasestorage.app',
    measurementId: 'G-468E0W9N4X',
  );
}
